-- Attendly / Attendance Recorder
-- Oracle SQL schema
-- Target: Oracle Database 19c+ / Oracle Database Free
-- Run as the application schema owner.

SET DEFINE OFF;

BEGIN
  EXECUTE IMMEDIATE 'DROP VIEW v_daily_class_summary';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP VIEW v_student_attendance_summary';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE attendance_audit CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE parent_alerts CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE attendance CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE class_sessions CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE students CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE classrooms CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

CREATE TABLE classrooms (
  classroom_id    VARCHAR2(20)   CONSTRAINT pk_classrooms PRIMARY KEY,
  classroom_name  VARCHAR2(120)  NOT NULL,
  latitude        NUMBER(10,7)   NOT NULL,
  longitude       NUMBER(10,7)   NOT NULL,
  radius_meters   NUMBER(8,2)    DEFAULT 50 NOT NULL,
  teacher_name    VARCHAR2(120),
  created_at      TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT ck_classroom_lat CHECK (latitude BETWEEN -90 AND 90),
  CONSTRAINT ck_classroom_lng CHECK (longitude BETWEEN -180 AND 180),
  CONSTRAINT ck_classroom_radius CHECK (radius_meters > 0)
);

CREATE TABLE students (
  student_id       VARCHAR2(20)   CONSTRAINT pk_students PRIMARY KEY,
  roll_number      VARCHAR2(30)   NOT NULL,
  student_name     VARCHAR2(120)  NOT NULL,
  classroom_id     VARCHAR2(20)   NOT NULL,
  parent_email     VARCHAR2(254),
  parent_phone     VARCHAR2(30),
  face_image_url   CLOB,
  status           VARCHAR2(10)   DEFAULT 'ACTIVE' NOT NULL,
  created_at       TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uq_students_roll UNIQUE (roll_number),
  CONSTRAINT fk_students_classroom FOREIGN KEY (classroom_id)
    REFERENCES classrooms(classroom_id),
  CONSTRAINT ck_students_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE class_sessions (
  session_id       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY
                   CONSTRAINT pk_class_sessions PRIMARY KEY,
  classroom_id     VARCHAR2(20)   NOT NULL,
  session_date     DATE           NOT NULL,
  start_time       TIMESTAMP      NOT NULL,
  end_time         TIMESTAMP,
  topic            VARCHAR2(200),
  session_status   VARCHAR2(12)   DEFAULT 'OPEN' NOT NULL,
  created_at       TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_sessions_classroom FOREIGN KEY (classroom_id)
    REFERENCES classrooms(classroom_id),
  CONSTRAINT uq_session_day UNIQUE (classroom_id, session_date),
  CONSTRAINT ck_session_status CHECK (session_status IN ('OPEN', 'COMPLETED', 'CANCELLED')),
  CONSTRAINT ck_session_time CHECK (end_time IS NULL OR end_time > start_time)
);

CREATE TABLE attendance (
  attendance_id       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY
                      CONSTRAINT pk_attendance PRIMARY KEY,
  session_id          NUMBER         NOT NULL,
  student_id          VARCHAR2(20)   NOT NULL,
  recorded_at         TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  status              VARCHAR2(10)   NOT NULL,
  confidence          NUMBER(5,2),
  latitude            NUMBER(10,7),
  longitude           NUMBER(10,7),
  verification_method VARCHAR2(20)   DEFAULT 'MANUAL' NOT NULL,
  synced_offline      CHAR(1)        DEFAULT 'N' NOT NULL,
  snapshot_url        VARCHAR2(1000),
  notes               VARCHAR2(1000),
  CONSTRAINT fk_attendance_session FOREIGN KEY (session_id)
    REFERENCES class_sessions(session_id) ON DELETE CASCADE,
  CONSTRAINT fk_attendance_student FOREIGN KEY (student_id)
    REFERENCES students(student_id),
  CONSTRAINT uq_attendance_student_session UNIQUE (session_id, student_id),
  CONSTRAINT ck_attendance_status CHECK (status IN ('PRESENT', 'ABSENT', 'LATE')),
  CONSTRAINT ck_attendance_confidence CHECK (confidence IS NULL OR confidence BETWEEN 0 AND 100),
  CONSTRAINT ck_attendance_lat CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90),
  CONSTRAINT ck_attendance_lng CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180),
  CONSTRAINT ck_attendance_method CHECK (verification_method IN ('FACE_RECOGNITION', 'MANUAL', 'OFFLINE_SYNC')),
  CONSTRAINT ck_attendance_sync CHECK (synced_offline IN ('Y', 'N'))
);

CREATE TABLE parent_alerts (
  alert_id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY
                    CONSTRAINT pk_parent_alerts PRIMARY KEY,
  attendance_id     NUMBER,
  student_id        VARCHAR2(20)   NOT NULL,
  alert_date        DATE           DEFAULT TRUNC(SYSDATE) NOT NULL,
  recipient_email   VARCHAR2(254)  NOT NULL,
  alert_status      VARCHAR2(10)   DEFAULT 'PENDING' NOT NULL,
  sent_at           TIMESTAMP,
  message           CLOB,
  created_at        TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_alert_attendance FOREIGN KEY (attendance_id)
    REFERENCES attendance(attendance_id) ON DELETE SET NULL,
  CONSTRAINT fk_alert_student FOREIGN KEY (student_id)
    REFERENCES students(student_id),
  CONSTRAINT uq_alert_student_day UNIQUE (student_id, alert_date),
  CONSTRAINT ck_alert_status CHECK (alert_status IN ('PENDING', 'SENT', 'FAILED'))
);

CREATE TABLE attendance_audit (
  audit_id        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY
                  CONSTRAINT pk_attendance_audit PRIMARY KEY,
  attendance_id   NUMBER,
  action_type     VARCHAR2(10) NOT NULL,
  old_status      VARCHAR2(10),
  new_status      VARCHAR2(10),
  changed_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  changed_by      VARCHAR2(128) DEFAULT SYS_CONTEXT('USERENV', 'SESSION_USER') NOT NULL,
  details         VARCHAR2(1000),
  CONSTRAINT ck_audit_action CHECK (action_type IN ('INSERT', 'UPDATE', 'DELETE'))
);

CREATE INDEX ix_students_classroom ON students(classroom_id);
CREATE INDEX ix_sessions_class_date ON class_sessions(classroom_id, session_date);
CREATE INDEX ix_attendance_student ON attendance(student_id);
CREATE INDEX ix_attendance_status ON attendance(status);
CREATE INDEX ix_alert_status ON parent_alerts(alert_status);

CREATE OR REPLACE VIEW v_student_attendance_summary AS
SELECT
  s.student_id,
  s.roll_number,
  s.student_name,
  c.classroom_name,
  COUNT(cs.session_id) AS total_sessions,
  SUM(CASE WHEN a.status = 'PRESENT' THEN 1 ELSE 0 END) AS present_count,
  SUM(CASE WHEN a.status = 'LATE' THEN 1 ELSE 0 END) AS late_count,
  SUM(CASE WHEN a.status = 'ABSENT' OR a.attendance_id IS NULL THEN 1 ELSE 0 END) AS absent_or_missing_count,
  ROUND(
    100 * SUM(CASE WHEN a.status IN ('PRESENT', 'LATE') THEN 1 ELSE 0 END)
    / NULLIF(COUNT(cs.session_id), 0),
    2
  ) AS attendance_percentage
FROM students s
JOIN classrooms c
  ON c.classroom_id = s.classroom_id
LEFT JOIN class_sessions cs
  ON cs.classroom_id = s.classroom_id
 AND cs.session_status <> 'CANCELLED'
LEFT JOIN attendance a
  ON a.session_id = cs.session_id
 AND a.student_id = s.student_id
GROUP BY s.student_id, s.roll_number, s.student_name, c.classroom_name;

CREATE OR REPLACE VIEW v_daily_class_summary AS
SELECT
  cs.session_id,
  cs.session_date,
  c.classroom_name,
  cs.topic,
  cs.session_status,
  COUNT(a.attendance_id) AS recorded_students,
  SUM(CASE WHEN a.status = 'PRESENT' THEN 1 ELSE 0 END) AS present_count,
  SUM(CASE WHEN a.status = 'LATE' THEN 1 ELSE 0 END) AS late_count,
  SUM(CASE WHEN a.status = 'ABSENT' THEN 1 ELSE 0 END) AS absent_count,
  ROUND(
    100 * SUM(CASE WHEN a.status IN ('PRESENT', 'LATE') THEN 1 ELSE 0 END)
    / NULLIF(COUNT(a.attendance_id), 0),
    2
  ) AS attendance_percentage
FROM class_sessions cs
JOIN classrooms c
  ON c.classroom_id = cs.classroom_id
LEFT JOIN attendance a
  ON a.session_id = cs.session_id
GROUP BY cs.session_id, cs.session_date, c.classroom_name, cs.topic, cs.session_status;

PROMPT Schema created successfully.
